public enum Degree {
    ORIENTACAO_A_OBJETOS,
    SISTEMAS_DIGITAIS,
    ESTRUTURA_DE_DADOS,
    MATEMATICA, 
    FUNDAMENTOS_DE_PROGRAMACAO,
    LOGICA,
    FILOSOFIA,
    ARQUITETURA_DE_COMPUTADORES,
    JAVA,
    BANCO_DE_DADOS,
    PYTHON,
    INTELIGENCIA_ARTIFICIAL
}